### ISSUE TITLE
Feature request: need golang lint

### ISSUE THREAD

**Issue by wilsonwu** [sentinel-group/sentinel-dashboard-k8s-operator#5]

**Comment by jnan806** [comment]
i want to contribute the go lint part, can i open a PR for Multiple-Commit-Authors ? 

OR separate this ISUUE to 2 parts for validate-code and deploy ?
validate-code for go lint and go test when some PR request merge.
deploy for build/push to docker/helm repo and deploy when do deploy version.

**Comment by wilsonwu** [comment]
Great, I think split this issue to 4 is better for contribution.

**Comment by wilsonwu** [comment]
> i want to contribute the go lint part, can i open a PR for Multiple-Commit-Authors ?
> 
> OR separate this ISUUE to 2 parts for validate-code and deploy ? validate-code for go lint and go test when some PR was committed. deploy for build/push to docker/helm repo and deploy when add a tag for version.

Done, splited.
